title: Intelligent Quantum Materials Lab (IQM Lab)
subtitle: Condensed Matter Theory & Computational Materials
email: lflin@utk.edu
google_scholar: https://scholar.google.com/citations?user=bvLzblkAAAAJ
url: "https://lflin1991.github.io"
baseurl: "/iqm-lab-homepage"
